services:
  rabbitmq:
    build: 
      context: ./rabbitmq
    container_name: rabbitmq-playground
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
      # Optional ports
      - "15692:15692"  # Prometheus metrics
      - "4369:4369"    # EPMD - Erlang Port Mapper Daemon
      - "25672:25672"  # inter-node and CLI tool communication
    networks:
      - rabbitmq_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  rabbitmq_net:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_logs:
